# Generated by Django 5.2.3 on 2025-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.TextField(default='Anonymous', verbose_name='User'),
        ),
    ]
