# Generated by Django 5.2.3 on 2025-07-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.TextField(verbose_name='User'),
        ),
    ]
